name: DITA Open Toolkit
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
baseurl: ""
sass:
    style: compressed
    sass_dir: css
exclude: ["gulpfile.js", "package.js", "node_modules"]

# MAJOR.MINOR
release: "2.2"
# MAJOR.MINOR.BUG
version: "2.2.5"
