title: DITA Open Toolkit
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
baseurl: ""
sass:
    style: compressed
    sass_dir: css

# Major & minor release version (2 digits)
release: "3.0"
# Maintenance version (normally 3 digits, 2 for initial minor release)
version: "3.0.3"

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - gulpfile.js
  - images/dita-ot_input-output.graffle
  - node_modules
  - package*.js*

# Enable redirects (#43)
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Preserve redirects (#44)
keep_files:
  - 3.0/dev_ref/html-customization-plugin-bundle-css.html
  - 3.0/dev_ref/migration.html
  - 3.0/dev_ref/plugin-newtranstype.html
  - dev/dev_ref/map-first-preprocessing.html
  - dev/dev_ref/migrating-ant-to-dita.html
  - dev/dev_ref/migration.html
  - dev/dev_ref/pdf-customization-best-practices.html
  - dev/dev_ref/plugin-addgeneratedtext.html
